version: "3.5"

services:
  php:
    image: uotz/php7.4-nginx
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - ./../Application/:/home/Application
      - ./../Domain/:/home/Domain
      - .:/home/app
      - ./.docker/nginx/default.conf:/etc/nginx/sites-available/default
    links:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
